# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"
    
sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

pre_install:
  - install -y --no-install-recommends python3-dev 
  - pip install --upgrade setuptools wheel cython numpy 

commands:
  - command: python setup.py build_ext --inplace
    cwd: .
