# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"
  apt_packages:
    - python3-dev
    - gcc
  resolve_project_dependencies: true
  requirements: docs/requirements.txt
  commands:
    - cd $READTHEDOCS_SOURCE_DIR
    - python setup.py build_ext --inplace
    
sphinx:
  configuration: docs/conf.py
  
python:
  install:
    - requirements: docs/requirements.txt
