# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"
    
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .


  before_install:
    - sudo apt-get update
    - sudo apt-get install -y build-essential python3-dev

  install:
    - pip: 
        - cython
        - setuptools
        - wheel

  post_install:
    - python setup.py build_ext --inplace

sphinx:
  configuration: docs/conf.py
