[tool.poetry.dev-dependencies]
sphinx = "^4.0"
sphinx_rtd_theme = "^1.0"

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "cython",
    "numpy"
]
build-backend = "setuptools.build_meta"
